###
GET http://localhost:8080/api/artists

###
GET http://localhost:8080/api/artists/1

###
GET http://localhost:8080/api/events

###
GET http://localhost:8080/api/events/1

###
GET http://localhost:8080/api/events/artist/4

###
GET http://localhost:8080/api/ratings/event/3


###
POST http://localhost:8080/api/ratings/3
Content-Type: application/json

{
    "stars": 5,
    "comment": "Absolutely loved it!"
}